name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出最新代码

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install poetry==1.7.1
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Build the project
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的令牌
        publish_dir: ./site  # 构建输出的目录
